
<!DOCTYPE html>
<html>
<head>
	<title>9 Paskaita (PHP)</title>
	<link rel="stylesheet" type="text/css" href="style2.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<body>
	<table>
  <tr>
    <th>X</th>
    <th>Y</th> 
    <th>Z</th>
    <th>Volume</th>
    <th></th>
  </tr>
  <tr>
    <td>1</td>
    <td>2</td>
    <td>1.5</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>2</td>
    <td>2</td>
    <td>1.5</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>3</td>
    <td>2</td>
    <td>1.5</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>4</td>
    <td>2</td>
    <td>1.5</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>5</td>
    <td>2</td>
    <td>1.5</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>6</td>
    <td>2</td>
    <td>1.5</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>7</td>
    <td>2</td>
    <td>1.5</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>8</td>
    <td>2</td>
    <td>1.5</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>9</td>
    <td>2</td>
    <td>1.5</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>10</td>
    <td>2</td>
    <td>1.5</td>
    <td></td>
    <td></td>
  </tr>
</table>
</body>
</html>
